export const ADDING_ITEM_TO_CART = "ADDING_ITEM_TO_CART";
export const ADDED_ITEM_TO_CART = "ADDED_ITEM_TO_CART";
export const ADDED_ITEM_TO_CART_ERROR = "ADDED_ITEM_TO_CART_ERROR";

export const FETCHING_CART_ITEMS = "FETCHING_CART_ITEMS";
export const FETCHED_CART_ITEMS = "FETCHED_CART_ITEMS";
export const FETCHING_CART_ITEMS_ERROR = "FETCHING_CART_ITEMS_ERROR";

export const DELETING_ITEM_FROM_CART = "DELETING_ITEM_FROM_CART";
export const DELETED_ITEM_FROM_CART = "DELETED_ITEM_FROM_CART";
export const DELETING_ITEM_FROM_CART_ERROR = "DELETING_ITEM_FROM_CART_ERROR";

export const UPDATING_ONE_ITEM_AMOUNT = "UPDATING_ONE_ITEM_AMOUNT";
export const UPDATED_ONE_ITEM_AMOUNT = "UPDATED_ONE_ITEM_AMOUNT";
export const UPDATING_ONE_ITEM_AMOUNT_ERROR = "UPDATING_ONE_ITEM_AMOUNT_ERROR";

export const ADDING_ONE_TO_ITEM_AMOUNT = "ADDING_ONE_TO_ITEM_AMOUNT";
export const ADDED_ONE_TO_ITEM_AMOUNT = "ADDED_ONE_TO_ITEM_AMOUNT";
export const ADDING_ONE_TO_ITEM_AMOUNT_ERROR =
  "ADDING_ONE_TO_ITEM_AMOUNT_ERROR";

export const REMOVING_ONE_ITEM_AMOUNT_FROM_CART =
  "REMOVING_ONE_ITEM_AMOUNT_FROM_CART";
export const REMOVED_ONE_ITEM_AMOUNT_FROM_CART =
  "REMOVED_ONE_ITEM_AMOUNT_FROM_CART";
export const REMOVING_ONE_ITEM_AMOUNT_FROM_CART_ERROR =
  "REMOVING_ONE_ITEM_AMOUNT_FROM_CART_ERROR";

export const EMPTYING_CART = "EMPTYING_CART";
export const EMPTIED_CART = "EMPTIED_CART";
export const EMPTYING_CART_ERROR = "EMPTYING_CART_ERROR";

// localStorage
export const SET_CART = "SET_CART";
