export const FETCHING_CATEGORIES = "FETCHING_CATEGORIES";
export const FETCHED_CATEGORIES = "FETCHED_CATEGORIES";
export const FETCHING_CATEGORIES_ERROR = "FETCHING_CATEGORIES_ERROR";

export const CREATING_CATEGORY = "CREATING_CATEGORY";
export const CREATED_CATEGORY = "CREATED_CATEGORY";
export const CREATED_CATEGORY_ERROR = "CREATED_CATEGORY_ERROR";

export const DELETING_CATEGORY = "DELETING_CATEGORY";
export const DELETED_CATEGORY = "DELETED_CATEGORY";
export const DELETING_CATEGORY_ERROR = "DELETING_CATEGORY_ERROR";

export const MODIFYING_CATEGORY = "MODIFYING_CATEGORY";
export const MODIFIED_CATEGORY = "MODIFIED_CATEGORY";
export const MODIFYING_CATEGORY_ERROR = "MODIFYING_CATEGORY_ERROR";
