export const FETCHING_ORDEN = "FETCHING_ORDEN";
export const FETCHED_ORDEN = "FETCHED_ORDEN";
export const FETCHING_ORDEN_ERROR = "FETCHING_ORDEN_ERROR";

export const CREATED_ORDEN = "CREATE_ORDEN";
export const CREATING_ORDEN = "CREATING_ORDEN";
export const CREATING_ORDEN_ERROR = "CREATING_ORDEN_ERROR";

export const DELETE_ORDEN = "DELETE_ORDEN";
export const DELETED_ORDEN = "DELETED_ORDEN";
export const DELETE_ORDEN_ERROR = "DELETE_ORDEN_ERROR";

export const MODIFYING_ORDEN = "MODIFYING_ORDEN";
export const MODIFIED_ORDEN = "MODIFIED_ORDEN";
export const MODIFYING_ORDEN_ERROR = "MODIFYING_ORDEN_ERROR";
