export const FETCHING_PRODUCTS = "FETCHING_PRODUCTS";
export const FETCHED_PRODUCTS = "FETCHED_PRODUCTS";
export const FETCHING_PRODUCTS_ERROR = "FETCHING_PRODUCTS_ERROR";

export const CREATING_PRODUCT = "CREATING_PRODUCT";
export const CREATED_PRODUCT = "CREATED_PRODUCT";
export const CREATING_PRODUCT_ERROR = "CREATING_PRODUCT_ERROR";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETED_PRODUCT = "DELETED_PRODUCT";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const GET_PRODUCT_BY_CATEGORIES = "GET_PRODUCT_BY_CATEGORIES";

export const MODIFYING_PRODUCT = "MODIFYING_PRODUCT";
export const MODIFIED_PRODUCT = "MODIFIED_PRODUCT";
export const MODIFYING_PRODUCT_ERROR = "MODIFYING_PRODUCT_ERROR";

export const FETCHING_LATEST_PRODUCTS_REVIEWS =
  "FETCHING_LATEST_PRODUCTS_REVIEWS";
export const FETCHED_LATEST_PRODUCTS_REVIEWS =
  "FETCHED_LATEST_PRODUCTS_REVIEWS";
export const FETCHING_LATEST_PRODUCTS_REVIEWS_ERROR =
  "FETCHING_LATEST_PRODUCTS_REVIEWS_ERROR";
