export const FETCHING_REVIEWS = "FETCHING_REVIEWS";
export const FETCHED_REVIEWS = "FETCHED_REVIEWS";
export const FETCHING_REVIEWS_ERROR = "FETCHING_REVIEWS_ERROR";

export const FETCHING_SPECIFIC_PRODUCT_REVIEWS =
  "FETCHING_SPECIFIC_PRODUCT_REVIEWS";
export const FETCHED_SPECIFIC_PRODUCT_REVIEWS =
  "FETCHED_SPECIFIC_PRODUCT_REVIEWS";
export const FETCHING_SPECIFIC_PRODUCT_REVIEWS_ERROR =
  "FETCHING_SPECIFIC_PRODUCT_REVIEWS_ERROR";
