export const FETCHING_USERS = "FETCHING_USERS";
export const FETCHED_USERS = "FETCHED_USERS";
export const FETCHING_USERS_ERROR = "FETCHING_USERS_ERROR";

export const FETCHING_USER_DATA = "FETCHING_USER_DATA";
export const FETCHED_USER_DATA = "FETCHED_USER_DATA";
export const FETCHING_USER_DATA_ERROR = "FETCHING_USER_DATA_ERROR";

export const CREATED_USER = "CREATED_USER";
export const CREATING_USER = "CREATING_USER";
export const CREATING_USER_ERROR = "CREATING_USER_ERROR";

export const LOGGING_USER = "LOGGING_USER";
export const LOGGED_USER_IN = "LOGGED_USER_IN";
export const LOGGING_USER_ERROR = "LOGGING_USER_ERROR";

export const LOGOUTED_USER = "LOGGING_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_ERROR = "LOGGING_USER_ERROR";

export const DELETE_USER = "DELETE_USER";
export const DELETED_USER = "DELETED_USER";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const MODIFYING_USER = "MODIFYING_USER";
export const MODIFIED_USER = "MODIFIED_USER";
export const MODIFYING_USER_ERROR = "MODIFYING_USER_ERROR";

export const FORCE_CHANGE_PASS = "FORCE_CHANGE_PASS"
export const CHANGE_PASS = "CHANGE_PASS"
export const PROMOVE_ADMIN = "PROMOVE_ADMIN"
